# Generated by Django 3.1.3 on 2020-12-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotnovel',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
