# Generated by Django 3.1.3 on 2020-12-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot_novel', '0002_auto_20201229_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotnovel',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotnovel',
            name='classification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotnovel',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotnovel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
